name: Build JOSS paper
on:
  push:
    branches:
      - main

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: ./joss-paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: paper
          path: ./joss-paper/paper.pdf
