name: Test package

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag of DOLFINx docker image"
        default: "nightly"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of DOLFINx docker image"
        default: "nightly"
        required: true
        type: string

  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  DEFAULT_TAG: nightly
  HDF5_MPI: "ON"
  HDF5_INCLUDEDIR: "/usr/include/hdf5/openmpi"
  H5PY_SETUP_REQUIRES: 0
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe

jobs:
  get_image_tag:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker_tag.outputs.image }}
    steps:
      - id: docker_tag
        run: echo "image=${{ inputs.tag || env.DEFAULT_TAG }}" >> $GITHUB_OUTPUT

  check-formatting:
    needs: get_image_tag
    uses: ./.github/workflows/check_formatting.yml
    with:
      tag: ${{ needs.get_image_tag.outputs.image }}

  create-datasets:
    uses: ./.github/workflows/create_legacy_data.yml
    with:
      artifact_name: "legacy_mpich"

  create-legacy-datasets:
    uses: ./.github/workflows/create_legacy_checkpoint.yml
    with:
      artifact_name: "legacy_checkpoint_mpich"

  test-code:
    runs-on: ubuntu-24.04
    needs:
      [create-datasets, create-legacy-datasets, check-formatting, get_image_tag]
    container: ghcr.io/fenics/test-env:current
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v7

      - name: Update pip
        run: python3 -m pip install --break-system-packages --upgrade pip setuptools

      - name: Configure HDF5 MPI Environment
        run: |
          # Evaluate architecture dynamically and write to GITHUB_ENV
          ARCH_TRIPLET=$(gcc -print-multiarch)
          echo "HDF5_LIBDIR=/usr/lib/${ARCH_TRIPLET}/hdf5/openmpi" >> $GITHUB_ENV

      - name: Download legacy data
        uses: actions/download-artifact@v8
        with:
          name: legacy_mpich
          path: ./legacy

      - name: Download legacy data
        uses: actions/download-artifact@v8
        with:
          name: legacy_checkpoint_mpich
          path: ./legacy_checkpoint

      - name: Install DOLFINx (stable)
        if: needs.get_image_tag.outputs.image == 'stable'
        uses: jorgensd/actions/install-dolfinx@v0.4
        with:
          adios2: v2.12.1
          petsc_arch: linux-gnu-real64-32
          dolfinx: v0.11.0.post0
          basix: v0.11.0
          ufl: 2026.1.0
          ffcx: v0.11.0
          working-directory: ${{ env.working-directory}}

      - name: Install DOLFINx (nightly)
        if: needs.get_image_tag.outputs.image == 'nightly'
        uses: jorgensd/actions/install-dolfinx@v0.4
        with:
          adios2: v2.12.1
          petsc_arch: linux-gnu-real64-32
          working-directory: ${{ env.working-directory}}

      - name: Install package
        run: python3 -m pip install --break-system-packages .[test]

      - name: Run tests
        run: |
          coverage run --rcfile=.coveragerc -m mpi4py -m pytest -xvs ./tests/

      - name: Run tests in parallel
        run: |
          mpirun -n 4 coverage run --rcfile=.coveragerc -m mpi4py -m pytest -xvs ./tests/

      - name: Combine coverage reports
        run: |
          coverage combine
          coverage report -m
          coverage html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report
          path: htmlcov
          if-no-files-found: error